import type { MediaSize } from "./site-types";

export const mediaVariants: Record<string, MediaSize[]> = {
  "Logo.jpg": [
    { filename: "gb-chiropractic-logo-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-logo-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-logo-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-logo-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-logo-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-logo-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-logo-200w.webp", width: 200, height: 200 },
    { filename: "gb-chiropractic-logo-256w.webp", width: 256, height: 257 },
    { filename: "gb-chiropractic-logo-320w.webp", width: 320, height: 320 },
    { filename: "gb-chiropractic-logo-384w.webp", width: 384, height: 385 },
    { filename: "gb-chiropractic-logo-480w.webp", width: 480, height: 480 },
    { filename: "gb-chiropractic-logo-640w.webp", width: 640, height: 642 },
  ],
  "logo-horizontal.jpg": [
    { filename: "gb-chiropractic-logo-horizontal-16w.webp", width: 16, height: 5 },
    { filename: "gb-chiropractic-logo-horizontal-32w.webp", width: 32, height: 9 },
    { filename: "gb-chiropractic-logo-horizontal-48w.webp", width: 48, height: 14 },
    { filename: "gb-chiropractic-logo-horizontal-64w.webp", width: 64, height: 19 },
    { filename: "gb-chiropractic-logo-horizontal-96w.webp", width: 96, height: 28 },
    { filename: "gb-chiropractic-logo-horizontal-128w.webp", width: 128, height: 38 },
    { filename: "gb-chiropractic-logo-horizontal-200w.webp", width: 200, height: 59 },
    { filename: "gb-chiropractic-logo-horizontal-256w.webp", width: 256, height: 76 },
    { filename: "gb-chiropractic-logo-horizontal-320w.webp", width: 320, height: 95 },
    { filename: "gb-chiropractic-logo-horizontal-384w.webp", width: 384, height: 114 },
    { filename: "gb-chiropractic-logo-horizontal-480w.webp", width: 480, height: 142 },
    { filename: "gb-chiropractic-logo-horizontal-640w.webp", width: 640, height: 189 },
    { filename: "gb-chiropractic-logo-horizontal-750w.webp", width: 750, height: 222 },
    { filename: "gb-chiropractic-logo-horizontal-768w.webp", width: 768, height: 227 },
    { filename: "gb-chiropractic-logo-horizontal-828w.webp", width: 828, height: 245 },
    { filename: "gb-chiropractic-logo-horizontal-1024w.webp", width: 1024, height: 303 },
    { filename: "gb-chiropractic-logo-horizontal-1080w.webp", width: 1080, height: 319 },
    { filename: "gb-chiropractic-logo-horizontal-1200w.webp", width: 1200, height: 355 },
    { filename: "gb-chiropractic-logo-horizontal-1280w.webp", width: 1280, height: 378 },
    { filename: "gb-chiropractic-logo-horizontal-1536w.webp", width: 1536, height: 454 },
  ],
  "About GB Chiro-1.jpg": [
    { filename: "gb-chiropractic-about-gb-chiro-1-16w.webp", width: 16, height: 12 },
    { filename: "gb-chiropractic-about-gb-chiro-1-32w.webp", width: 32, height: 24 },
    { filename: "gb-chiropractic-about-gb-chiro-1-48w.webp", width: 48, height: 35 },
    { filename: "gb-chiropractic-about-gb-chiro-1-64w.webp", width: 64, height: 47 },
    { filename: "gb-chiropractic-about-gb-chiro-1-96w.webp", width: 96, height: 71 },
    { filename: "gb-chiropractic-about-gb-chiro-1-128w.webp", width: 128, height: 94 },
    { filename: "gb-chiropractic-about-gb-chiro-1-256w.webp", width: 256, height: 189 },
    { filename: "gb-chiropractic-about-gb-chiro-1-384w.webp", width: 384, height: 283 },
    { filename: "gb-chiropractic-about-gb-chiro-1-640w.webp", width: 640, height: 471 },
    { filename: "gb-chiropractic-about-gb-chiro-1-750w.webp", width: 750, height: 552 },
    { filename: "gb-chiropractic-about-gb-chiro-1-828w.webp", width: 828, height: 610 },
    { filename: "gb-chiropractic-about-gb-chiro-1-1080w.webp", width: 1080, height: 795 },
    { filename: "gb-chiropractic-about-gb-chiro-1-1200w.webp", width: 1200, height: 884 },
    { filename: "gb-chiropractic-about-gb-chiro-1-1920w.webp", width: 1920, height: 1414 },
    { filename: "gb-chiropractic-about-gb-chiro-1-2048w.webp", width: 2048, height: 1508 },
    { filename: "gb-chiropractic-about-gb-chiro-1-3840w.webp", width: 3840, height: 2828 },
  ],
  "Home Page.jpg": [
    { filename: "gb-chiropractic-home-page-16w.webp", width: 16, height: 11 },
    { filename: "gb-chiropractic-home-page-32w.webp", width: 32, height: 21 },
    { filename: "gb-chiropractic-home-page-48w.webp", width: 48, height: 32 },
    { filename: "gb-chiropractic-home-page-64w.webp", width: 64, height: 43 },
    { filename: "gb-chiropractic-home-page-96w.webp", width: 96, height: 64 },
    { filename: "gb-chiropractic-home-page-128w.webp", width: 128, height: 86 },
    { filename: "gb-chiropractic-home-page-256w.webp", width: 256, height: 171 },
    { filename: "gb-chiropractic-home-page-384w.webp", width: 384, height: 257 },
    { filename: "gb-chiropractic-home-page-640w.webp", width: 640, height: 429 },
    { filename: "gb-chiropractic-home-page-750w.webp", width: 750, height: 502 },
    { filename: "gb-chiropractic-home-page-828w.webp", width: 828, height: 555 },
    { filename: "gb-chiropractic-home-page-1080w.webp", width: 1080, height: 724 },
    { filename: "gb-chiropractic-home-page-1200w.webp", width: 1200, height: 804 },
    { filename: "gb-chiropractic-home-page-1920w.webp", width: 1920, height: 1286 },
    { filename: "gb-chiropractic-home-page-2048w.webp", width: 2048, height: 1372 },
  ],
  "Meet the chiro-1.jpg": [
    { filename: "gb-chiropractic-meet-the-chiro-1-16w.webp", width: 16, height: 12 },
    { filename: "gb-chiropractic-meet-the-chiro-1-32w.webp", width: 32, height: 24 },
    { filename: "gb-chiropractic-meet-the-chiro-1-48w.webp", width: 48, height: 37 },
    { filename: "gb-chiropractic-meet-the-chiro-1-64w.webp", width: 64, height: 49 },
    { filename: "gb-chiropractic-meet-the-chiro-1-96w.webp", width: 96, height: 73 },
    { filename: "gb-chiropractic-meet-the-chiro-1-128w.webp", width: 128, height: 98 },
    { filename: "gb-chiropractic-meet-the-chiro-1-256w.webp", width: 256, height: 196 },
    { filename: "gb-chiropractic-meet-the-chiro-1-384w.webp", width: 384, height: 293 },
    { filename: "gb-chiropractic-meet-the-chiro-1-640w.webp", width: 640, height: 489 },
    { filename: "gb-chiropractic-meet-the-chiro-1-750w.webp", width: 750, height: 573 },
    { filename: "gb-chiropractic-meet-the-chiro-1-828w.webp", width: 828, height: 633 },
    { filename: "gb-chiropractic-meet-the-chiro-1-1080w.webp", width: 1080, height: 825 },
    { filename: "gb-chiropractic-meet-the-chiro-1-1200w.webp", width: 1200, height: 917 },
    { filename: "gb-chiropractic-meet-the-chiro-1-1920w.webp", width: 1920, height: 1467 },
    { filename: "gb-chiropractic-meet-the-chiro-1-2048w.webp", width: 2048, height: 1565 },
    { filename: "gb-chiropractic-meet-the-chiro-1-3840w.webp", width: 3840, height: 2935 },
  ],
  "Headache and migraine care.jpg": [
    { filename: "gb-chiropractic-headache-and-migraine-care-16w.webp", width: 16, height: 11 },
    { filename: "gb-chiropractic-headache-and-migraine-care-32w.webp", width: 32, height: 21 },
    { filename: "gb-chiropractic-headache-and-migraine-care-48w.webp", width: 48, height: 32 },
    { filename: "gb-chiropractic-headache-and-migraine-care-64w.webp", width: 64, height: 43 },
    { filename: "gb-chiropractic-headache-and-migraine-care-96w.webp", width: 96, height: 64 },
    { filename: "gb-chiropractic-headache-and-migraine-care-128w.webp", width: 128, height: 85 },
    { filename: "gb-chiropractic-headache-and-migraine-care-256w.webp", width: 256, height: 171 },
    { filename: "gb-chiropractic-headache-and-migraine-care-384w.webp", width: 384, height: 256 },
    { filename: "gb-chiropractic-headache-and-migraine-care-640w.webp", width: 640, height: 427 },
    { filename: "gb-chiropractic-headache-and-migraine-care-750w.webp", width: 750, height: 500 },
    { filename: "gb-chiropractic-headache-and-migraine-care-828w.webp", width: 828, height: 552 },
    { filename: "gb-chiropractic-headache-and-migraine-care-1080w.webp", width: 1080, height: 720 },
    { filename: "gb-chiropractic-headache-and-migraine-care-1200w.webp", width: 1200, height: 800 },
  ],
  "Sports Injury Management.jpg": [
    { filename: "gb-chiropractic-sports-injury-management-16w.webp", width: 16, height: 11 },
    { filename: "gb-chiropractic-sports-injury-management-32w.webp", width: 32, height: 21 },
    { filename: "gb-chiropractic-sports-injury-management-48w.webp", width: 48, height: 32 },
    { filename: "gb-chiropractic-sports-injury-management-64w.webp", width: 64, height: 43 },
    { filename: "gb-chiropractic-sports-injury-management-96w.webp", width: 96, height: 64 },
    { filename: "gb-chiropractic-sports-injury-management-128w.webp", width: 128, height: 85 },
    { filename: "gb-chiropractic-sports-injury-management-256w.webp", width: 256, height: 171 },
    { filename: "gb-chiropractic-sports-injury-management-384w.webp", width: 384, height: 256 },
    { filename: "gb-chiropractic-sports-injury-management-640w.webp", width: 640, height: 427 },
    { filename: "gb-chiropractic-sports-injury-management-750w.webp", width: 750, height: 500 },
    { filename: "gb-chiropractic-sports-injury-management-828w.webp", width: 828, height: 552 },
    { filename: "gb-chiropractic-sports-injury-management-1080w.webp", width: 1080, height: 720 },
    { filename: "gb-chiropractic-sports-injury-management-1200w.webp", width: 1200, height: 800 },
  ],
  "Spinal adjustment and manipulation.jpg": [
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-spinal-adjustment-and-manipulation-828w.webp", width: 828, height: 828 },
  ],
  "Pregnancy chiropractic care.jpg": [
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-16w.webp", width: 16, height: 11 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-32w.webp", width: 32, height: 21 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-48w.webp", width: 48, height: 32 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-64w.webp", width: 64, height: 43 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-96w.webp", width: 96, height: 64 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-128w.webp", width: 128, height: 85 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-256w.webp", width: 256, height: 171 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-384w.webp", width: 384, height: 256 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-640w.webp", width: 640, height: 427 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-750w.webp", width: 750, height: 500 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-828w.webp", width: 828, height: 552 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-1080w.webp", width: 1080, height: 720 },
    { filename: "gb-chiropractic-pregnancy-chiropractic-care-1200w.webp", width: 1200, height: 800 },
  ],
  "Rehab & strengthening exercises.jpg": [
    { filename: "gb-chiropractic-rehab-strengthening-exercises-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-rehab-strengthening-exercises-828w.webp", width: 828, height: 828 },
  ],
  "Wellness and preventative care.jpg": [
    { filename: "gb-chiropractic-wellness-and-preventative-care-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-wellness-and-preventative-care-828w.webp", width: 828, height: 828 },
  ],
  "Joint pain and mobility support.jpg": [
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-joint-pain-and-mobility-support-828w.webp", width: 828, height: 828 },
  ],
  "New patients-1.jpg": [
    { filename: "gb-chiropractic-new-patients-1-16w.webp", width: 16, height: 19 },
    { filename: "gb-chiropractic-new-patients-1-32w.webp", width: 32, height: 37 },
    { filename: "gb-chiropractic-new-patients-1-48w.webp", width: 48, height: 56 },
    { filename: "gb-chiropractic-new-patients-1-64w.webp", width: 64, height: 74 },
    { filename: "gb-chiropractic-new-patients-1-96w.webp", width: 96, height: 112 },
    { filename: "gb-chiropractic-new-patients-1-128w.webp", width: 128, height: 149 },
    { filename: "gb-chiropractic-new-patients-1-256w.webp", width: 256, height: 298 },
    { filename: "gb-chiropractic-new-patients-1-384w.webp", width: 384, height: 446 },
    { filename: "gb-chiropractic-new-patients-1-640w.webp", width: 640, height: 744 },
    { filename: "gb-chiropractic-new-patients-1-750w.webp", width: 750, height: 872 },
    { filename: "gb-chiropractic-new-patients-1-828w.webp", width: 828, height: 962 },
    { filename: "gb-chiropractic-new-patients-1-1080w.webp", width: 1080, height: 1255 },
    { filename: "gb-chiropractic-new-patients-1-1200w.webp", width: 1200, height: 1395 },
    { filename: "gb-chiropractic-new-patients-1-1920w.webp", width: 1920, height: 2231 },
    { filename: "gb-chiropractic-new-patients-1-2048w.webp", width: 2048, height: 2380 },
  ],
  "Paediatric chiropractic care-2.jpg": [
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-paediatric-chiropractic-care-2-828w.webp", width: 828, height: 828 },
  ],
  "What to expect.jpg": [
    { filename: "gb-chiropractic-what-to-expect-16w.webp", width: 16, height: 23 },
    { filename: "gb-chiropractic-what-to-expect-32w.webp", width: 32, height: 45 },
    { filename: "gb-chiropractic-what-to-expect-48w.webp", width: 48, height: 68 },
    { filename: "gb-chiropractic-what-to-expect-64w.webp", width: 64, height: 90 },
    { filename: "gb-chiropractic-what-to-expect-96w.webp", width: 96, height: 135 },
    { filename: "gb-chiropractic-what-to-expect-128w.webp", width: 128, height: 181 },
    { filename: "gb-chiropractic-what-to-expect-256w.webp", width: 256, height: 361 },
    { filename: "gb-chiropractic-what-to-expect-384w.webp", width: 384, height: 542 },
    { filename: "gb-chiropractic-what-to-expect-640w.webp", width: 640, height: 903 },
    { filename: "gb-chiropractic-what-to-expect-750w.webp", width: 750, height: 1058 },
    { filename: "gb-chiropractic-what-to-expect-828w.webp", width: 828, height: 1168 },
    { filename: "gb-chiropractic-what-to-expect-1080w.webp", width: 1080, height: 1524 },
    { filename: "gb-chiropractic-what-to-expect-1200w.webp", width: 1200, height: 1693 },
    { filename: "gb-chiropractic-what-to-expect-1920w.webp", width: 1920, height: 2709 },
    { filename: "gb-chiropractic-what-to-expect-2048w.webp", width: 2048, height: 2890 },
  ],
  "Neck and back pain relief 1.jpg": [
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-neck-and-back-pain-relief-1-828w.webp", width: 828, height: 828 },
  ],
  "Posture correction.jpg": [
    { filename: "gb-chiropractic-posture-correction-16w.webp", width: 16, height: 16 },
    { filename: "gb-chiropractic-posture-correction-32w.webp", width: 32, height: 32 },
    { filename: "gb-chiropractic-posture-correction-48w.webp", width: 48, height: 48 },
    { filename: "gb-chiropractic-posture-correction-64w.webp", width: 64, height: 64 },
    { filename: "gb-chiropractic-posture-correction-96w.webp", width: 96, height: 96 },
    { filename: "gb-chiropractic-posture-correction-128w.webp", width: 128, height: 128 },
    { filename: "gb-chiropractic-posture-correction-256w.webp", width: 256, height: 256 },
    { filename: "gb-chiropractic-posture-correction-384w.webp", width: 384, height: 384 },
    { filename: "gb-chiropractic-posture-correction-640w.webp", width: 640, height: 640 },
    { filename: "gb-chiropractic-posture-correction-750w.webp", width: 750, height: 750 },
    { filename: "gb-chiropractic-posture-correction-828w.webp", width: 828, height: 828 },
  ],
  "Reception.jpg": [
    { filename: "gb-chiropractic-reception-16w.webp", width: 16, height: 14 },
    { filename: "gb-chiropractic-reception-32w.webp", width: 32, height: 28 },
    { filename: "gb-chiropractic-reception-48w.webp", width: 48, height: 43 },
    { filename: "gb-chiropractic-reception-64w.webp", width: 64, height: 57 },
    { filename: "gb-chiropractic-reception-96w.webp", width: 96, height: 85 },
    { filename: "gb-chiropractic-reception-128w.webp", width: 128, height: 114 },
    { filename: "gb-chiropractic-reception-256w.webp", width: 256, height: 228 },
    { filename: "gb-chiropractic-reception-384w.webp", width: 384, height: 341 },
    { filename: "gb-chiropractic-reception-640w.webp", width: 640, height: 569 },
    { filename: "gb-chiropractic-reception-750w.webp", width: 750, height: 667 },
    { filename: "gb-chiropractic-reception-828w.webp", width: 828, height: 736 },
    { filename: "gb-chiropractic-reception-1080w.webp", width: 1080, height: 960 },
    { filename: "gb-chiropractic-reception-1200w.webp", width: 1200, height: 1067 },
    { filename: "gb-chiropractic-reception-1920w.webp", width: 1920, height: 1707 },
    { filename: "gb-chiropractic-reception-2048w.webp", width: 2048, height: 1820 },
    { filename: "gb-chiropractic-reception-3840w.webp", width: 3840, height: 3413 },
  ],
  "Room.jpg": [
    { filename: "gb-chiropractic-room-16w.webp", width: 16, height: 18 },
    { filename: "gb-chiropractic-room-32w.webp", width: 32, height: 37 },
    { filename: "gb-chiropractic-room-48w.webp", width: 48, height: 55 },
    { filename: "gb-chiropractic-room-64w.webp", width: 64, height: 73 },
    { filename: "gb-chiropractic-room-96w.webp", width: 96, height: 110 },
    { filename: "gb-chiropractic-room-128w.webp", width: 128, height: 146 },
    { filename: "gb-chiropractic-room-256w.webp", width: 256, height: 292 },
    { filename: "gb-chiropractic-room-384w.webp", width: 384, height: 438 },
    { filename: "gb-chiropractic-room-640w.webp", width: 640, height: 731 },
    { filename: "gb-chiropractic-room-750w.webp", width: 750, height: 856 },
    { filename: "gb-chiropractic-room-828w.webp", width: 828, height: 945 },
    { filename: "gb-chiropractic-room-1080w.webp", width: 1080, height: 1233 },
    { filename: "gb-chiropractic-room-1200w.webp", width: 1200, height: 1370 },
    { filename: "gb-chiropractic-room-1920w.webp", width: 1920, height: 2192 },
    { filename: "gb-chiropractic-room-2048w.webp", width: 2048, height: 2338 },
    { filename: "gb-chiropractic-room-3840w.webp", width: 3840, height: 4384 },
  ],
  "Practice Entry.jpg": [
    { filename: "gb-chiropractic-practice-entry-16w.webp", width: 16, height: 21 },
    { filename: "gb-chiropractic-practice-entry-32w.webp", width: 32, height: 43 },
    { filename: "gb-chiropractic-practice-entry-48w.webp", width: 48, height: 64 },
    { filename: "gb-chiropractic-practice-entry-64w.webp", width: 64, height: 85 },
    { filename: "gb-chiropractic-practice-entry-96w.webp", width: 96, height: 128 },
    { filename: "gb-chiropractic-practice-entry-128w.webp", width: 128, height: 171 },
    { filename: "gb-chiropractic-practice-entry-256w.webp", width: 256, height: 341 },
    { filename: "gb-chiropractic-practice-entry-384w.webp", width: 384, height: 512 },
    { filename: "gb-chiropractic-practice-entry-640w.webp", width: 640, height: 853 },
    { filename: "gb-chiropractic-practice-entry-750w.webp", width: 750, height: 1000 },
    { filename: "gb-chiropractic-practice-entry-828w.webp", width: 828, height: 1104 },
    { filename: "gb-chiropractic-practice-entry-1080w.webp", width: 1080, height: 1440 },
    { filename: "gb-chiropractic-practice-entry-1200w.webp", width: 1200, height: 1600 },
    { filename: "gb-chiropractic-practice-entry-1920w.webp", width: 1920, height: 2560 },
    { filename: "gb-chiropractic-practice-entry-2048w.webp", width: 2048, height: 2731 },
    { filename: "gb-chiropractic-practice-entry-3840w.webp", width: 3840, height: 5120 },
  ],
  "Street View.jpg": [
    { filename: "gb-chiropractic-street-view-16w.webp", width: 16, height: 21 },
    { filename: "gb-chiropractic-street-view-32w.webp", width: 32, height: 43 },
    { filename: "gb-chiropractic-street-view-48w.webp", width: 48, height: 64 },
    { filename: "gb-chiropractic-street-view-64w.webp", width: 64, height: 85 },
    { filename: "gb-chiropractic-street-view-96w.webp", width: 96, height: 128 },
    { filename: "gb-chiropractic-street-view-128w.webp", width: 128, height: 171 },
    { filename: "gb-chiropractic-street-view-256w.webp", width: 256, height: 341 },
    { filename: "gb-chiropractic-street-view-384w.webp", width: 384, height: 512 },
    { filename: "gb-chiropractic-street-view-640w.webp", width: 640, height: 853 },
    { filename: "gb-chiropractic-street-view-750w.webp", width: 750, height: 1000 },
    { filename: "gb-chiropractic-street-view-828w.webp", width: 828, height: 1104 },
    { filename: "gb-chiropractic-street-view-1080w.webp", width: 1080, height: 1440 },
    { filename: "gb-chiropractic-street-view-1200w.webp", width: 1200, height: 1600 },
    { filename: "gb-chiropractic-street-view-1920w.webp", width: 1920, height: 2560 },
    { filename: "gb-chiropractic-street-view-2048w.webp", width: 2048, height: 2731 },
    { filename: "gb-chiropractic-street-view-3840w.webp", width: 3840, height: 5120 },
  ],
};
